apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort  # Change LoadBalancer to NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30259 # Use the same NodePort as before
