apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
<<<<<<< HEAD
  type: NodePort
=======
  type: LoadBalancer 
>>>>>>> cb120bbe3818fc31b3aae175102d14ca92f86432
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 80 # Use the same NodePort as before
